theme: jekyll-theme-architect
show_downloads: "true"
github:
  3d_view: https://github.com/eva-social-robot/3dmodels
  3d_url: https://github.com/eva-social-robot/3dmodels/archive/refs/heads/main.zip
  core_view: https://github.com/amitjans/Eva
  core_url: https://github.com/amitjans/Eva/archive/refs/heads/master.zip
  eyes_app_v: 1.2.2-rc
  eyes_app_url: https://github.com/amitjans/eva-app/releases/download/v1.2.2-rc/Eva-1.0.0-armv7l.AppImage
  eyes_code_view: https://github.com/amitjans/eva-app
  eyes_code_url: https://github.com/amitjans/eva-app/archive/refs/heads/master.zip
  neck_view: https://github.com/amitjans/AXSimpleTest
  neck_url: https://github.com/amitjans/AXSimpleTest/archive/refs/heads/master.zip
